### ISSUE TITLE
compatibility with  http ^1.1.0

### ISSUE THREAD

**Issue by Parasankitbisht** [sefidgaran/signalr_client#66]
```
Because signalr_netcore 1.3.6 depends on http ^0.13.6 and no versions of signalr_netcore match >1.3.6 <2.0.0, signalr_netcore ^1.3.6 requires http ^0.13.6.
So, because "App Name "depends on both http ^1.1.0 and signalr_netcore ^1.3.6, version solving failed.
```

**Comment by samialfattani** [comment]
Why did you close the issue ?? 
I'm facing the same problem of compatibility with google_fonts plugin:
`
Because no versions of signalr_netcore match >1.3.6 <2.0.0 and signalr_netcore 1.3.6 depends on http ^0.13.6, signalr_netcore ^1.3.6 requires http ^0.13.6.
And because google_fonts >=4.0.5 depends on http ^1.0.0, signalr_netcore ^1.3.6 is incompatible with google_fonts >=4.0.5.
So, because astarar depends on both google_fonts ^6.1.0 and signalr_netcore ^1.3.6, version solving failed.
`
